//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountDetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDetailsTable
    {
        public int accountNumber { get; set; }
        public string accountholderName { get; set; }
        public string accountType { get; set; }
        public string location { get; set; }
        public Nullable<int> phoneNumber { get; set; }
        public Nullable<int> pincode { get; set; }
    }
}
